version: "3.3"
services:
  ingress: #container naam
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro #dubbel punt is scheiding van parameters, ro = read-only, rw=read-write
      - ./frontend:/var/www/static/:ro
    ports:
      - 127.0.0.1:8000:80
    depends_on:
      - auth
      - chat
  auth:
    build: ./authAPI/.
  chat:
    build: ./chatAPI/.